### ISSUE TITLE
Question about licensing

### ISSUE THREAD

**Issue by alcuadrado** [xf00f/web3x#10]
Hi @xf00f,

I analyzed all the dependencies from `package.json`, and none of them is GPL. They are MIT, BSD, ISC and Apache2, all of them are permissive licenses. 

I noticed that there's also some parts of ethers.js inlined here, but that's also MIT. I'm not sure if there are parts of this project copied from web3.js. If it's only the API, using another license should be fine.

I'm wondering what's the reason to license this project as GLPv3. IMO that would inhibit adoption, as it can't be used in proprietary software, nor in project that don't agree with GLP's copyleft or don't want to be in this same position (eg: me).

**Comment by xf00f** [comment]
It started as a direct fork from web3.js beta 36. It became a big refactor / rewrite so large parts of the codebase can probably be licensed under MIT, but there are still large portions that need work. Theres still a lot of tech debt there, but perhaps once (if) that gets rewritten it can be properly MIT licensed. Until then I think we're out of luck.

**Comment by xf00f** [comment]
Having said that, and skimming over the code, I'd say there isn't *that* much of the original left. Some stuff around `confirm-transaction.ts` `sign-transaction.ts` and subscriptions. I'm not really familiar enough with licensing to be able to say at what point the prior work is no longer the prior work.

**Comment by xf00f** [comment]
Also, it's distributed as LGPLv3, which is more permissive than GPLv3. In other words you can use it for commercial use. To quote Wikipedia:

"The license allows developers and companies to use and integrate software released under the LGPL into their own (even proprietary) software without being required by the terms of a strong copyleft license to release the source code of their own components. "

**Comment by alcuadrado** [comment]
Sorry, I was confused. I'm OK with LGPL. I prefer MIT because it's simpler, but LGPL is fine.
