### ISSUE TITLE
Bad type in JsonRPCResponse

### ISSUE THREAD

**Issue by alcuadrado** [xf00f/web3x#13]
Hi,

While working on adding some basic EIP-1193 compatibility I discovered a typing error [here](https://github.com/xf00f/web3x/blob/master/src/providers/index.ts#L31).

The correct type is:

```ts
error?: {
  code: number;
  message: string;
  data?: any;
}
```

See section [5.1 of the JSONRPC 2.0 sepc](https://www.jsonrpc.org/specification) for more info.

**Comment by xf00f** [comment]
@alcuadrado Thanks. Fixed locally. I'm also looking at some EIP-1193 compatibility. I've created a gitter at https://gitter.im/web3x if you'd like to discuss.

**Comment by xf00f** [comment]
This has been merged.
