### ISSUE TITLE
Some possible changes to EIP1193 and a call about them

### ISSUE THREAD

**Issue by alcuadrado** [xf00f/web3x#27]
Hey @xf00f,

I'm opening this issue because between a few interested parties we had an open call today to discuss possible changes on EIP1193 and its release schedule. The call wasn't very representative, so nothing was decided, and we are scheduling another one. 

I think you may be interested in joining the next call, or the [discord channel](https://discord.gg/J4WHas) where this is being discussed. There are also some interesting discussions going on on [ethereum magicians provider ring](https://ethereum-magicians.org/c/working-groups/provider-ring), and you may want to check them.

Best,
Patricio

**Comment by xf00f** [comment]
Thanks Patricio. I'm in the discord and will monitor.
