### ISSUE TITLE
Split up getBlock into getBlockWithTransactions and getBlockWithoutTransactions?

### ISSUE THREAD

**Issue by SirensOfTitan** [xf00f/web3x#29]
Not quite sure of great naming, but the original web3 API for getting the block could be improved.
`getBlock(number, true || false // if we want full transactions)`
...could be split s.t. basically:
`getBlockWithTransactions(number): BlockResponse<TransactionResponse>` 
`getBlockWithoutTransactions(number): BlockResponse<Buffer>`

One might be able to use some typescript wizardry too here and not split up the method, some typescript pseudocode: 
```typescript
function getBlock<TGetFullTransactions extends boolean>(blockNumber: number | string | ..., includeFullTransactions: TGetFullTransactions): TGetFullTransactions extends true ? BlockResponse<TransactionResponse> : BlockResponse<Buffer>;
```

... happy to submit a PR if we agree this would be a good optimization.

**Comment by xf00f** [comment]
@SirensOfTitan I solved this as follows:

```javascript
  public async getBlock(block: BlockType | BlockHash, returnTxs?: false): Promise<BlockResponse<Buffer>>;
  public async getBlock(block: BlockType | BlockHash, returnTxs?: true): Promise<BlockResponse<TransactionResponse>>;
  public async getBlock(block: BlockType | BlockHash, returnTxs?: boolean): Promise<BlockResponse> {
    return await this.send(this.request.getBlock(block, returnTxs));
  }
```

Which is kind of a combination of the two ideas you suggested. It should now return the correct specific type dependent on the second parameter. Please check deployed version `v3.0.4`.

Thanks for reporting.
