### ISSUE TITLE
Re-license to MIT

### ISSUE THREAD

**Issue by webmaster128** [xf00f/web3x#39]
As started in https://github.com/xf00f/web3x/issues/34#issuecomment-472777000, there is the idea of relicensing this project as MIT. I think this is a very valuable step and makes this library much more attractive than others in the Ethereum space.

I'm opening this issue
* to get visibility over the state of the relicensing
* to express that all contributions from my side (not much yet but who knows what) are free to be licensed as MIT

**Comment by xf00f** [comment]
@webmaster128 Relicensing work has begun on https://github.com/xf00f/web3x/tree/xf/v4.0.0

So far MIT applies to `web3x-codegen` `web3x-evm` `web3x-node-example` `web3x-webpack-example`.

**Comment by webmaster128** [comment]
Amazing!

**Comment by xf00f** [comment]
While ultimately I'd like all of web3x to be MIT, I'm not going to risk any license violations. The main library will remain LGPL for now. I have at least restructured web3x into a multipackage monorepo to allow this gradual shift going forward.
