### ISSUE TITLE
eth.getAccounts returns wrong type

### ISSUE THREAD

**Issue by SirensOfTitan** [xf00f/web3x#47]
Expectation: Eth.getAccounts returns items of the type `Address[]`
Actuality: Eth.getAccounts returns checksum-formatted addresses in `string[]` form.

Formatting wrong in: https://github.com/xf00f/web3x/blob/ef2ff658c7c9ff5c578a460a1c37210574e62f7f/src/eth/eth-request-payloads.ts#L122
Given the following type: https://github.com/xf00f/web3x/blob/a3ace7a9fdf1afc4533d5a87165f029272e67199/src/eth/eth.ts#L114

**Comment by xf00f** [comment]
Should be resolved in 3.0.11.
