### ISSUE TITLE
Number returns are seen as string instead of BN.

### ISSUE THREAD

**Issue by hickscorp** [xf00f/web3x#58]
Given a standard ERC20 token, and its definition for `web3x-codegen` to parse:

```
    "Token": {
      "source": "files",
      "abiFile": "./node_modules/contracts/build/abi/Token.abi",
      "initDataFile": "./node_modules/contracts/build/abi/Token.bin"
    }
```

The generated TS file is incorrect:

```
totalSupply(): TxCall<string>;
```

Given that the ABI definition says the function returns a uin256, shouldn't this return a BN allowing for greater abstraction?

**Comment by xf00f** [comment]
Basically, yes. However web3.js always returns strings, so this is a hangover from web3.js compatability. Version 5 of web3x will support returning JSBI (basically native BigInt) instances for all integers. If the user then requires BN specific extended functionality it will be to the developer to use this library.

https://github.com/xf00f/web3x/tree/xf/v5.0.0

**Comment by hickscorp** [comment]
@xfoof Thanks a lot for the explanation, I'm really happy to see the direction this library is going. Great job.

Is there a RC we can use for 5.0?

**Comment by xf00f** [comment]
I doubt the above will work. The packages are carefully constructed and don't mimic the repo.
Sorry, but you'll probably have to wait for an official release.

**Comment by hickscorp** [comment]
@xf00f Was there any development on this? Is there a way to get integer return / parameters that are closer to the solidity types yet? For us it's a big blocker and we don't know how to use the version 5 of web3x before it releases.
