### ISSUE TITLE
Why checking for outputs to define if a function is constant ?

### ISSUE THREAD

**Issue by megaturbo** [xf00f/web3x#63]
Why checking for outputs to define if a function is constant ? 

`web3x-codegen` defines [here](https://github.com/xf00f/web3x/blob/5c7bc624cfa1de59d64bf135c23d9862a5cce4e0/web3x-codegen/src/index.ts#L311) a function constant if there are outputs. Why not rather checking for:
```typescript
if (definition.constant)
```

A function can be state-modifying even if it has output, right ? I just wanted to understand why. I can do a PR if that makes sense to use the `constant` keyword of the `ABI`.

I know it doesn't change anything since the solidity compiler outputs the `stateMutability` parameters, but the `vyper` compiler doesn't. So that would help to be vyper-compatible.

**Comment by xf00f** [comment]
I think this is incorrect, perhaps an incorrect assumption at some point on my part around return values not being accessible on transactions. There is no way to read a return value from a transaction, only events. However it is possible for a state modifying call to return a value which could be read by another smart contract. I'll accept a PR. Thanks.

**Comment by alcuadrado** [comment]
> use the `constant` keyword of the `ABI`.
> 
> I know it doesn't change anything since the solidity compiler outputs the `stateMutability` parameters, but the `vyper` compiler doesn't. So that would help to be vyper-compatible.

I think you should check either of them. Something like `abi.constant || abi.stateMutability === 'payable' || abi.stateMutability === 'nonpayable'`, since acording to [solidity's doc](https://solidity.readthedocs.io/en/v0.5.11/abi-spec.html) `constant` will be removed in the future.

**Comment by megaturbo** [comment]
@alcuadrado I think that the case when `stateMutability` is set is already handled [here](https://github.com/xf00f/web3x/blob/5c7bc624cfa1de59d64bf135c23d9862a5cce4e0/web3x-codegen/src/index.ts#L326)

Btw I did a PR, feel free to review it

**Comment by xf00f** [comment]
Should be fixed in v4.0.6
