### ISSUE TITLE
Unhandled exception warning in Account.proptotype.sendTransaction

### ISSUE THREAD

**Issue by alcuadrado** [xf00f/web3x#8]
If no `gas` is provided to `Account.proptotype.sendTransaction` an exception is thrown, but not handled. In fact, any exception [thrown here](https://github.com/xf00f/web3x/blob/master/src/accounts/account.ts#L46,L47) will lead to the same situation.

I guess the expected behavior would be for the `Account` to estimate the gas by calling the provider. This is an opinionated alternative though. The simplest alternative is for the error to be forwarded to the returned `PromiEvent`.

Here's a minimal production script:
```ts
import { HttpProvider } from 'web3x/providers';
import { Eth } from 'web3x/eth';
import { Account } from 'web3x/accounts';

async function main() {
  const provider = new HttpProvider('http://localhost:8545');
  const eth = Eth.fromProvider(provider);

  const localAccount = Account.create(eth);
  
  //This should throw something like "sender doesn't have enough funds to send tx"
  await localAccount.sendTransaction({to: localAccount.address, value: 1});
}

main().catch(console.error);
```

**Comment by xf00f** [comment]
Hi @alcuadrado, thanks for raising this. Please check if new deployment v1.2.2 resolves this issue for you. It ensures the exception is correctly propagated.

It doesn't default to estimating the gas, but I'm unsure if that's the correct approach. web3.js just says default is "To be determined". I'm unsure if there is a reason they don't just call estimate gas to fill in a default. Perhaps it opens up an opportunity to accidentally spend a load of ETH on a bugged out tx, so they were being protective by forcing user to be explicit.

**Comment by alcuadrado** [comment]
Hi @xf00f, thanks for the quick answer! 

Unfortunately this didn't solve it. Changing https://github.com/xf00f/web3x/blob/master/src/accounts/account.ts#L48 to `}).catch(error => defer.reject(error));` works.

Going back to wether to estimate or not, I think it's a good approach to make gas estimation a responsibility of the user, so they can keep control of those requests. Creating and using something like `GasEstimationAccount` should be trivial, so not a big deal. 

There are some typing improvements to be made there. I'll open another issue for that.

**Comment by xf00f** [comment]
Apologies, I did fix an error, it just wasn't your error. Please try latest deployment v1.2.3.

**Comment by alcuadrado** [comment]
It works now, thank you!
