### ISSUE TITLE
Some Account methods incorrectly receive Tx object

### ISSUE THREAD

**Issue by alcuadrado** [xf00f/web3x#9]
`Account.prototype.sendTransaction` and `Account.prototype.sendTransaction` receive `Tx` objects as their first parameter. They should receive something like:

```ts
interface LocalAccountTx {
    nonce?: string | number;
    chainId?: string | number;
    to?: string;
    data?: string;
    value?: string | number;
    gas: string | number;
    gasPrice?: string | number;
}
```

as the `from` param doesn't make sense here, and the `gas` param is required.

**Comment by xf00f** [comment]
On second thoughts the docs there do not specify gas in the examples. Let me dig into that deeper.

**Comment by xf00f** [comment]
@alcuadrado On branch v2.0.0 I have enforced gas as a necessary property. I'll wait a bit before merging this branch in, so if you spot any other issues let me know.

**Comment by xf00f** [comment]
This has been merged.
